/**
 * Resolve a football team name to a real club logo URL from football-logos.cc.
 *
 * `logos-manifest.json` (generated by scripts/build-logos-manifest.mjs) maps a
 * site slug -> { c: country, h: 256px content hash }. Given a team name we
 * generate slug candidates (exact, override, prefix/suffix-stripped, national
 * team) and return the first that exists, built into the immutable 256x256 CDN
 * URL. The browser HTTP-caches each asset for a year (Cache-Control: immutable),
 * so there is no custom cache layer. Returns null on a miss; callers fall back
 * to the initials badge.
 *
 * Must be rendered via <img> (not fetch): the CDN sends no CORS header.
 */
import manifest from "./logos-manifest.json";
import type { TeamRef } from "./v2/types";

// `s` (optional) is the real file slug when it differs from the manifest key,
// e.g. the alias "portugal-national-team" -> "portuguese-football-federation".
type Entry = { c: string; h: string; s?: string };
const MANIFEST = manifest as Record<string, Entry>;

/** Mirrors slugify in app/lib/v2/queries.ts, with diacritics folded. */
function slugify(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// Club/league prefix tokens the site drops (e.g. "AC Milan" -> "milan").
const PREFIX = new Set([
  "fc", "afc", "cf", "ac", "as", "ss", "ssc", "sc", "us", "rc", "rcd", "sd",
  "ud", "cd", "sv", "tsg", "vfl", "vfb", "fsv", "sg", "fk", "if", "bk", "ca",
]);
const SUFFIX = new Set(["fc", "cf", "sc", "club", "calcio"]);
// Connector words the site drops mid-name (e.g. "Atlético de Madrid").
const STOP = new Set(["de", "of", "the", "du", "da", "und", "le", "la"]);

// Names whose clean slug doesn't match the site's slug. Keyed by slugify(name).
const OVERRIDE: Record<string, string> = {
  "tottenham-hotspur": "tottenham",
  "wolverhampton-wanderers": "wolves",
  wolverhampton: "wolves",
  "brighton-and-hove-albion": "brighton",
  "brighton-hove-albion": "brighton",
  internazionale: "inter",
  "inter-milan": "inter",
  "ac-milan": "milan",
  "as-roma": "roma",
  "bayern-munich": "bayern-munchen",
  "fc-bayern-munich": "bayern-munchen",
  "athletic-bilbao": "athletic-club",
  "athletic-club-bilbao": "athletic-club",
  "real-betis-balompie": "real-betis",
  "olympique-de-marseille": "marseille",
  psg: "paris-saint-germain",
};

// National-team country-name variants -> the site's category segment. Lets a
// country name resolve to its "{category}-national-team" alias in the manifest.
const COUNTRY_ALIAS: Record<string, string> = {
  "united-states": "usa",
  "united-states-of-america": "usa",
  "korea-republic": "south-korea",
  "republic-of-korea": "south-korea",
  "korea-dpr": "north-korea",
  "ivory-coast": "cote-d-ivoire",
  ireland: "republic-of-ireland",
  czechia: "czech-republic",
  bosnia: "bosnia-and-herzegovina",
  "united-arab-emirates": "uae",
  "dr-congo": "congo-dr",
  "democratic-republic-of-congo": "congo-dr",
  "cape-verde": "cabo-verde",
  turkiye: "turkey",
};

/** First slug matching a generated candidate, or null. */
function resolveSlug(name: string): string | null {
  const base = slugify(name);
  if (!base) return null;

  const tried = new Set<string>();
  const hit = (slug: string): string | null => {
    if (!slug || tried.has(slug)) return null;
    tried.add(slug);
    return MANIFEST[slug] ? slug : null;
  };

  // Denoise: drop a leading prefix token, a trailing suffix token, connector
  // words, and pure-numeric tokens (e.g. "Bayer 04 Leverkusen" -> bayer-leverkusen).
  let toks = base.split("-");
  if (toks.length > 1 && PREFIX.has(toks[0])) toks = toks.slice(1);
  if (toks.length > 1 && SUFFIX.has(toks[toks.length - 1])) toks = toks.slice(0, -1);
  toks = toks.filter((t) => !STOP.has(t) && !/^\d+$/.test(t));
  const core = toks.join("-");

  // 1. explicit override (raw name, then denoised)
  for (const k of [base, core]) {
    if (OVERRIDE[k]) {
      const s = hit(OVERRIDE[k]);
      if (s) return s;
    }
  }

  // 2. exact, then denoised
  let s = hit(base) ?? hit(core);
  if (s) return s;

  // 3. national team (World Cup names are bare country names)
  s = hit(`${core}-national-team`);
  if (s) return s;
  const alias = COUNTRY_ALIAS[core];
  if (alias) {
    s = hit(`${alias}-national-team`);
    if (s) return s;
  }

  // 4. drop trailing tokens one at a time (Tottenham Hotspur -> tottenham)
  for (let end = toks.length - 1; end >= 1; end--) {
    s = hit(toks.slice(0, end).join("-"));
    if (s) return s;
  }

  return null;
}

/** Build a 256x256 logo URL from a resolved manifest key. */
function urlFor(key: string): string {
  const { c, h, s } = MANIFEST[key];
  return `https://assets.football-logos.cc/logos/${c}/256x256/${s ?? key}.${h}.png`;
}

/** Build the 256x256 logo URL for a team, or null if unknown. */
export function logoUrl(team: TeamRef | string): string | null {
  const name = typeof team === "string" ? team : team.name;
  const slug = resolveSlug(name);
  return slug ? urlFor(slug) : null;
}

// Our competition slugs / short codes -> the site's tournament or league slug.
const COMPETITION_SLUG: Record<string, string> = {
  "premier-league": "english-premier-league",
  pl: "english-premier-league",
  "la-liga": "la-liga",
  pd: "la-liga",
  laliga: "la-liga",
  bundesliga: "bundesliga",
  bl1: "bundesliga",
  "serie-a": "serie-a",
  sa: "serie-a",
  "ligue-1": "ligue-1",
  fl1: "ligue-1",
  "champions-league": "uefa-champions-league",
  cl: "uefa-champions-league",
  "europa-league": "uefa-europa-league",
  el: "uefa-europa-league",
  "world-cup": "fifa-world-cup-2026",
  wc: "fifa-world-cup-2026",
};

/** Logo URL for a competition by our slug or short code, or null if unknown. */
export function competitionLogoUrl(idOrCode: string): string | null {
  const key = COMPETITION_SLUG[idOrCode.toLowerCase()];
  return key && MANIFEST[key] ? urlFor(key) : null;
}
